[package]
name = "rust_mdr_utils"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
serde = { version = "1.0", features = ["derive", "rc"] }
serde-wasm-bindgen = "0.6"
serde_json = "1.0"
console_error_panic_hook = { version = "0.1", optional = true }

[features]
default = []
parallel = ["wasm-bindgen-rayon"]

[dependencies.wasm-bindgen-rayon]
version = "1.2"
optional = true

[dev-dependencies]
wasm-bindgen-test = "0.3" 