name: PR Auto Assign

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  pr-auto-assign:
    name: PR Auto Assign
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    if: github.event.pull_request.draft == false

    steps:
      - name: PR Auto Assign
        uses: danielswensson/auto-assign-owner-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
