name: Release to npm

on:
  push:
    branches: [main]

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      version-changed: ${{ steps.check.outputs.version-changed }}
      version: ${{ steps.check.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check if version changed
        id: check
        working-directory: packages/next-eval
        run: |
          # Get current version from package.json
          CURRENT_VERSION=$(node -p "require('./package.json').version")

          # Get previous version from package.json in the previous commit
          git checkout HEAD~1 -- package.json 2>/dev/null || echo "No previous commit"
          PREVIOUS_VERSION=$(node -p "require('./package.json').version" 2>/dev/null || echo "0.0.0")

          # Reset to current version
          git checkout HEAD -- package.json

          echo "Previous version: $PREVIOUS_VERSION"
          echo "Current version: $CURRENT_VERSION"

          if [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
            echo "Version changed from $PREVIOUS_VERSION to $CURRENT_VERSION"
            echo "version-changed=true" >> $GITHUB_OUTPUT
            echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          else
            echo "Version unchanged"
            echo "version-changed=false" >> $GITHUB_OUTPUT
            echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          fi

  release:
    needs: check-version
    if: needs.check-version.outputs.version-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run tests
        run: bun test

      - name: Build package
        run: bun run build
        working-directory: packages/next-eval

      - name: Setup npm registry
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          echo "registry=https://registry.npmjs.org/" >> ~/.npmrc

      - name: Publish to npm
        run: npm publish --access public
        working-directory: packages/next-eval
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.check-version.outputs.version }}
          name: Release v${{ needs.check-version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ## Changes

            Auto-generated release for @wordbricks/next-eval version ${{ needs.check-version.outputs.version }}

            ### Installation

            ```bash
            npm install @wordbricks/next-eval@latest
            # or
            bun add @wordbricks/next-eval@latest
            # or
            yarn add @wordbricks/next-eval@latest
            ```

            ### Usage

            ```typescript
            import { HTMLProcessor, evaluateExtractions } from '@wordbricks/next-eval';

            // Process HTML
            const processor = new HTMLProcessor(html);
            const { slimHtml, hierarchicalJson, flatJson } = processor.process();

            // Evaluate extractions
            const results = evaluateExtractions(groundTruth, predictions);
            ```

            For more details, see the [documentation](https://github.com/wordbricks/next-eval).
          draft: false
          prerelease: false
