name: Slash Command

on:
  issue_comment:
    types: [created]

jobs:
  slashCommand:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command
        uses: peter-evans/slash-command-dispatch@main
        with:
          token: ${{ secrets.PAT }}
          commands: |
            rebase
